GET http://localhost:5000/health

###

GET http://localhost:5000/users

###

POST http://localhost:5000/users
Content-Type: application/json

{
  "username": "user2",
  "password": "pass2"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "user2",
  "password": "pass2"
}

###
GET http://localhost:5000/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWF0IjoxNjI2MjM1MzI2fQ.5pC86KCz-BoKEstnr8CXQNqZmZhMFwHOUrKS_Z2xlkM
